#!/bin/sh

rm -rf pkg/client/model
cp -rf storage/model pkg/client/model
find pkg/client/model -type f -exec sed -i '1s|^|// Code generated by go generate; DO NOT EDIT.\n// This file was generated by scripts/copy-models-to-client.sh\n\n|' {} \;
